### ISSUE TITLE
WindowsLive External login issue

### ISSUE THREAD

**Issue by TjebbeVQ** [projectsend/projectsend#1012]
I have a similar issue to #872 but with the windows authentication.
I'm guessing WindowsLive acctually means O365 authentication.

Using the above mentioned error printing I get following error:

`Fatal error: Uncaught Hybridauth\Exception\InvalidApplicationCredentialsException: Your application id is required in order to connect to WindowsLive in /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php:253 Stack trace: #0 /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php(109): Hybridauth\Adapter\OAuth2->configure() #1 /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Hybridauth.php(141): Hybridauth\Adapter\AbstractAdapter->__construct() #2 /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Hybridauth.php(101): Hybridauth\Hybridauth->getAdapter() #3 /data/sites/web/TEST/www/upl/includes/Classes/Auth.php(133): Hybridauth\Hybridauth->authenticate() #4 /data/sites/web/TEST/www/upl/process.php(27): ProjectSend\Classes\Auth->socialLogin() #5 {main} thrown in /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php on line 253`

It looks to me like the application cannot retrieve the AppID or Secret key which is entered in the settings.

Quoting the ID's does not help. But using the ID's from O365 in Google or Facebook actually attempts to login via those providers but is unable since it's not a valid App ID (since it's the one from O365)...

Any guide to get Windows authentication working? We are running the latest version r1295.

Thanks

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
