### ISSUE TITLE
Mysql error while installing

### ISSUE THREAD

**Issue by Tallerik** [projectsend/projectsend#1112]
After the second installation step where you can configure the URL and the admin user, the installation fails.

System information:
```
uname -a
Linux hostname 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

nginx -v
nginx version: nginx/1.18.0 (Ubuntu)

php -v
PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )

mysql -V
/usr/sbin/mysqld  Ver 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))

All system requirements from the README are met
```

### Error:
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups(`id`) ON DELETE CASCADE ON UPDATE CASCADE ) ENGINE=InnoDB DEFAUL' at line 9 in /var/www/html/docs/includes/functions.php:20 Stack trace: #0 /var/www/html/docs/includes/functions.php(20): PDO->prepare() #1 /var/www/html/docs/install/index.php(168): try_query() #2 {main}

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups(`id`) ON DELETE CASCADE ON UPDATE CASCADE ) ENGINE=InnoDB DEFAUL' at line 10 in /var/www/html/docs/includes/functions.php:20 Stack trace: #0 /var/www/html/docs/includes/functions.php(20): PDO->prepare() #1 /var/www/html/docs/install/index.php(168): try_query() #2 {main}

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups(`id`) ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY (`id`) ' at line 10 in /var/www/html/docs/includes/functions.php:20 Stack trace: #0 /var/www/html/docs/includes/functions.php(20): PDO->prepare() #1 /var/www/html/docs/install/index.php(168): try_query() #2 {main}

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups(`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`folder' at line 12 in /var/www/html/docs/includes/functions.php:20 Stack trace: #0 /var/www/html/docs/includes/functions.php(20): PDO->prepare() #1 /var/www/html/docs/install/index.php(168): try_query() #2 {main}
```

![grafik](https://user-images.githubusercontent.com/18576088/177206712-68ced442-05e3-4d6a-ac00-3e3166f98507.png)

**Comment by ignacionelson** [comment]
Sorry, couldn't reproduce the issue!
