### ISSUE TITLE
Blank page - fatal error

### ISSUE THREAD

**Issue by techauthoruk** [projectsend/projectsend#1192]
Hi

I have a new install of ProjectSend; after install I can access the login screen fine. I log in and then I just get a blank screen. I enabled debug mode, and it throws lots of errors about deprecations:

```php
Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /home/mark/www/files/includes/functions.php on line 966

Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /home/mark/www/files/includes/functions.php on line 966

Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /home/mark/www/files/includes/functions.php on line 966
```
but I don't think this is the issue. I get a warning and fatal error at the bottom of the page:

```php
Warning: fopen(/home/mark/www/files/cache/35b5e218ab8866cfc379018788847681): Failed to open stream: Permission denied in /home/mark/www/files/includes/functions.php on line 167

Fatal error: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /home/mark/www/files/includes/functions.php:168 Stack trace: #0 /home/mark/www/files/includes/functions.php(168): fwrite() #1 /home/mark/www/files/includes/updates.functions.php(18): get_json() #2 /home/mark/www/files/includes/core.update.php(17): get_latest_version_data() #3 /home/mark/www/files/header.php(45): require_once('/home/mark/www/...') #4 /home/mark/www/files/dashboard.php(14): include_once('/home/mark/www/...') #5 {main} thrown in /home/mark/www/files/includes/functions.php on line 168
```

No idea what is causing this - can anyone help?

My install:

Ubuntu 22.04LTS server
Apache 2.4.52
PHP 8.1.13
MariaDB 10.6.11

**Comment by techauthoruk** [comment]
OK

Figured it out - it was a folder permissions issue.

Closing this
