### ISSUE TITLE
Large file upload fails

### ISSUE THREAD

**Issue by Slopz** [projectsend/projectsend#1204]
I'm running ProjectSend in Docker. Whenever I try to upload a large file, the upload page reloads to a blank page. I've tried multiple browsers and multiple devices, so it's 100% not a browser issue. 

[Video Demo](http://link.nbbn.cloud/VTpho)

Error spat out
```
Uncaught RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at Object.e [as typeOf] (plupload.full.min.js:13:1)
    at new n (plupload.full.min.js:13:1)
    at n.slice (plupload.full.min.js:14:1)
    at n.exec (plupload.full.min.js:13:1)
    at n.shimExec (plupload.full.min.js:13:1)
    at n.exec (plupload.full.min.js:13:1)
    at n.slice (plupload.full.min.js:13:1)
    at r.uploadChunk (plupload.full.min.js:29:1)
    at r.uploadChunk (plupload.full.min.js:29:1)
e @ plupload.full.min.js:13
n @ plupload.full.min.js:13
slice @ plupload.full.min.js:14
exec @ plupload.full.min.js:13
shimExec @ plupload.full.min.js:13
exec @ plupload.full.min.js:13
slice @ plupload.full.min.js:13
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
uploadChunk @ plupload.full.min.js:29
jquery.min.js?v=3.6.1:2 [Violation] 'submit' handler took 14245ms
```
I'm guessing this might be some kind of a timeout issue with PHP?
I've tried setting these
```
memory_limit = 5120M
post_max_size = 0
max_execution_time = 300
```
in `/confic/php/php-local.ini` hoping one of them would fix the issue but no luck. 

Also, I've heard there's an issue with PHP and downloading large files so I tried switching to X-Accel by adding 
```
location /serve-file {
    internal;
    alias /app/www/public/upload/;
}
``` 
to `/config/nginx/site-confs/default.conf` but I don't think it did anything. I have no idea on how to enable XSendFile or X-Accel as I'm new to this. I haven't tried using XSendFile as apparently it needs some kind of a module to be installed which I have no idea on how to do. 

Thanks!

**Comment by Slopz** [comment]
Setting the chunk size from 1mb to 3mb in `upload.php` seems to have done the trick. But now I wonder, what is the ideal chunk size? anything higher than 3mb and the uploads freezes with 502 error on the last chunk, lower than 3mb and I get the initial error. Is there a way to determine the ideal size or is 3mb it in my case?

**Comment by thewriteway** [comment]
I couldn't upload large files until editing the max client max body in the nginx config file:
` sudo nano /etc/nginx/nginx.conf`
Change or add the entry in the http section to the larger size you need:
`client_max_body_size 50M;`

**Comment by manhluong** [comment]
For my use case, to enable upload of large files, I removed altogether the `client_max_body_size` from `nginx.conf` and set a very high upload size in the `projectsend/includes/sys.config.php`, like 50 gb:

`define('MAX_FILESIZE',51200); `

Using version `r1605 `.

I can indeed upload very large files.

I am not using docker, I installed directly.

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
