### ISSUE TITLE
First use and Fatal error on the Public.php page

### ISSUE THREAD

**Issue by Jeziel41** [projectsend/projectsend#1210]
Hello, I did an automatic installation through my host and everything went very well. But when I want to access the public page I have an error 1210:

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1210 Incorrect arguments to mysqld_stmt_execute in /home/clients/5b8889ce2fb82c7c86cfb3073d973e92/sites/challenger.afiwai.com/archives/includes/functions.public.php:92 Stack trace: #0 /home/clients/5b8889ce2fb82c7c86cfb3073d973e92/sites/challenger.afiwai.com/archives/includes/functions.public.php(92): PDOStatement->execute(Array) #1 /home/clients/5b8889ce2fb82c7c86cfb3073d973e92/sites/challenger.afiwai.com/archives/includes/functions.groups.php(231): get_public_files(Array) #2 /home/clients/5b8889ce2fb82c7c86cfb3073d973e92/sites/challenger.afiwai.com/archives/templates/default/public-list.php(37): count_public_files_not_in_groups() #3 /home/clients/5b8889ce2fb82c7c86cfb3073d973e92/sites/challenger.afiwai.com/archives/public.php(64): require('/home/clients/5...') #4 {main} thrown in /home/clients/5b8889ce2fb82c7c86cfb3073d973e92/sites/challenger.afiwai.com/archives/includes/functions.public.php on line 92

**Comment by ignacionelson** [comment]
Sorry, this is a known bug with the latest version. As a temp workaround, create a public group. It does not need to have any files or clients,but it needs to exist

**Comment by Jeziel41** [comment]
Thank you for this super fast response. I have already created a public group but the page still does not work. Maybe I have something else to do?

https://dodgechallenger.fr/archives/public.php

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
