### ISSUE TITLE
PHP 8.2 breaks cron.php (PHP 8.1 works just fine) also, suggested crontab entry is wrong?

### ISSUE THREAD

**Issue by ehawman** [projectsend/projectsend#1213]
Firstly, ProjectSend suggests `* /5 * * * /usr/bin/php /var/www/projectsend/cron.php key={mykeyishere}  >/dev/null`

My system (ubuntu server) rejects that as an incorrect cron config and [crontab.guru concurs](https://crontab.guru/#*_/5_*_*_*).

I believe you're looking for [`*/5 * * * *`](https://crontab.guru/every-5-minutes)?

Secondly, the cronjob isn't working properly. I have verified that `/usr/bin/php` and `/var/www/projectsend/cron.php` both exist in those paths. 

`php --version` returns `PHP 8.2.1 (cli)`.

I tested `* * * * * /usr/bin/php /var/www/projectsend/cron.php key={mykeyishere}  1>> /home/ehawman/ps_cron.log 2>>/home/ehawman/ps_cron_err.log` to try and peel back the curtain.  Once the files are created:

`File: ps_cron.log   <EMPTY>`
`File: ps_cron_err.log   <EMPTY>`

Ok let's try `* * * * * /usr/bin/php8.1 /var/www/projectsend/cron.php key={mykeyishere}  1>> /home/ehawman/ps_cron.log 2>>/home/ehawman/ps_cron_err.log`

Not only is there content in `ps_cron.log`, but the emails are being sent. Cool. 👍 

What about  `* * * * * /usr/bin/php8.2 /var/www/projectsend/cron.php key={mykeyishere}  1>> /home/ehawman/ps_cron.log 2>>/home/ehawman/ps_cron_err.log`?

Back to blank logs and no emails.

So yes something in the change from PHP 8.1 to 8.2 broke `cron.php`'s workflow.

I'm currently running  `* * * * * /usr/bin/php8.1 /var/www/projectsend/cron.php key={mykeyishere}  >/dev/null`. I'll hop back to straight `/usr/bin/php` when you close this ticket 😄

**Comment by leleobhz** [comment]
I confirm this issue with PHP 8.2, with exit code 255:

```
bash-5.1$ /usr/bin/php -d error_reporting=-1 /opt/app-root/src/cron.php key=<my_key_here>
bash-5.1$ echo $?
255
bash-5.1$ /usr/bin/php --version
PHP 8.2.13 (cli) (built: Nov 21 2023 09:55:59) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies
bash-5.1$

```

**Comment by leleobhz** [comment]
> I confirm this issue with PHP 8.2, with exit code 255:
> 
> ```
> bash-5.1$ /usr/bin/php -d error_reporting=-1 /opt/app-root/src/cron.php key=<my_key_here>
> bash-5.1$ echo $?
> 255
> bash-5.1$ /usr/bin/php --version
> PHP 8.2.13 (cli) (built: Nov 21 2023 09:55:59) (NTS gcc x86_64)
> Copyright (c) The PHP Group
> Zend Engine v4.2.13, Copyright (c) Zend Technologies
>     with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies
> bash-5.1$
> ```

But also happens with PHP 8.1:

```
bash-5.1$ /usr/bin/php -d error_reporting=-1 /opt/app-root/src/cron.php key=<my_key_here> ; echo $?
255
bash-5.1$ php --version
PHP 8.1.30 (cli) (built: Sep 26 2024 17:35:59) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.30, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.30, Copyright (c), by Zend Technologies
bash-5.1$
```

**Comment by ignacionelson** [comment]
Thank you! I've changed the example in commit feac7bc
Are you getting anything in the error log when using php 8.2? Maybe something comes up if you activate debug mode 
https://docs.projectsend.org/about/troubleshooting/debug-mode

**Comment by leleobhz** [comment]
> Thank you! I've changed the example in commit [feac7bc](https://github.com/projectsend/projectsend/commit/feac7bc875d29f85ca4d44d4c0a9b424b59e4bae) Are you getting anything in the error log when using php 8.2? Maybe something comes up if you activate debug mode https://docs.projectsend.org/about/troubleshooting/debug-mode

I do not use cron with docker, instead, use https://github.com/mcuadros/ofelia

About debug, with PHP 8.1, ran like this:

```
bash-5.1$ /usr/bin/php -d error_reporting=-1 /opt/app-root/src/cron.php key=<my_key> ; echo $?
PHP Warning:  Undefined array key "" in /opt/app-root/src/includes/Classes/i18n.php on line 272

Warning: Undefined array key "" in /opt/app-root/src/includes/Classes/i18n.php on line 272
PHP Warning:  Trying to access array offset on value of type null in /opt/app-root/src/includes/Classes/i18n.php on line 272

Warning: Trying to access array offset on value of type null in /opt/app-root/src/includes/Classes/i18n.php on line 272
PHP Warning:  Trying to access array offset on value of type null in /opt/app-root/src/includes/Classes/i18n.php on line 272

Warning: Trying to access array offset on value of type null in /opt/app-root/src/includes/Classes/i18n.php on line 272
PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /opt/app-root/src/includes/Classes/i18n.php on line 295

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /opt/app-root/src/includes/Classes/i18n.php on line 295
PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/app-root/src/includes/Classes/i18n.php:272) in /opt/app-root/src/includes/active.session.php on line 7
PHP Warning:  Cannot modify header information - headers already sent by (output started at /opt/app-root/src/includes/Classes/i18n.php:272) in /opt/app-root/src/includes/active.session.php on line 8
PHP Fatal error:  Uncaught Error: Undefined constant "CURRENT_USER_ID" in /opt/app-root/src/includes/functions.php:1080
Stack trace:
#0 /opt/app-root/src/includes/Classes/OrphanFiles.php(89): file_is_allowed('1663188036-e85b...')
#1 /opt/app-root/src/includes/Classes/OrphanFiles.php(34): ProjectSend\Classes\OrphanFiles->findOrphanFiles(Array)
#2 /opt/app-root/src/includes/Classes/Cron.php(198): ProjectSend\Classes\OrphanFiles->getFiles()
#3 /opt/app-root/src/includes/Classes/Cron.php(82): ProjectSend\Classes\Cron->runTaskDeleteOrphanFiles()
#4 /opt/app-root/src/cron.php(5): ProjectSend\Classes\Cron->runTasks()
#5 {main}
  thrown in /opt/app-root/src/includes/functions.php on line 1080

Warning: Cannot modify header information - headers already sent by (output started at /opt/app-root/src/includes/Classes/i18n.php:272) in /opt/app-root/src/includes/active.session.php on line 7

Warning: Cannot modify header information - headers already sent by (output started at /opt/app-root/src/includes/Classes/i18n.php:272) in /opt/app-root/src/includes/active.session.php on line 8

Fatal error: Uncaught Error: Undefined constant "CURRENT_USER_ID" in /opt/app-root/src/includes/functions.php:1080
Stack trace:
#0 /opt/app-root/src/includes/Classes/OrphanFiles.php(89): file_is_allowed('1663188036-e85b...')
#1 /opt/app-root/src/includes/Classes/OrphanFiles.php(34): ProjectSend\Classes\OrphanFiles->findOrphanFiles(Array)
#2 /opt/app-root/src/includes/Classes/Cron.php(198): ProjectSend\Classes\OrphanFiles->getFiles()
#3 /opt/app-root/src/includes/Classes/Cron.php(82): ProjectSend\Classes\Cron->runTaskDeleteOrphanFiles()
#4 /opt/app-root/src/cron.php(5): ProjectSend\Classes\Cron->runTasks()
#5 {main}
  thrown in /opt/app-root/src/includes/functions.php on line 1080
255
bash-5.1$

```

**Comment by ignacionelson** [comment]
Thank you! I hope this change fixes the issue
https://github.com/projectsend/projectsend/commit/7f230183862566b98be74a0d2afe85a01bb78dba

**Comment by leleobhz** [comment]
@ignacionelson thank you!

That said, there is a proper instruction to build from source? Since I mantain a projectsend container platform ( https://github.com/ZenithTecnologia/projectsend-docker ), may be useful to build (even stable releases) from Git itself insead parsing webpage, etc, etc, etc.

Thanks!

**Comment by leleobhz** [comment]
@ignacionelson hello!

You fix indeed works as expected, but a syntax needs a fix and i submit a PR to fix it. Do you mind accept it?

Thanks!

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
