### ISSUE TITLE
Registration Bug with potential fix

### ISSUE THREAD

**Issue by bmartin13** [projectsend/projectsend#1247]
Running r1605 in docker from this docker image:
https://hub.docker.com/r/linuxserver/projectsend

Found a bug when registering with a new user... error thrown:

Fatal error: Uncaught Error: Undefined constant "ProjectSend\Classes\CURRENT_USER_LEVEL" in /app/www/public/includes/Classes/Users.php:842 

Stack trace: 
#0 /app/www/public/includes/Classes/Users.php(464): ProjectSend\Classes\Users->limitUploadToSave() 
#1 /app/www/public/register.php(44): ProjectSend\Classes\Users->create() 
#2 {main} thrown in /app/www/public/includes/Classes/Users.php on line 842

PROPOSED FIX on line 842 of /app/www/public/includes/Classes/Users.php

current: 
        if (CURRENT_USER_LEVEL == 7) {
            return;
        }
proposed: 
        if (!defined('CURRENT_USER_LEVEL') or CURRENT_USER_LEVEL == 7) {
            return;
        }

**Comment by serg499** [comment]
Thank you! Also have the same bug and @bmartin13 solution seems working. I was finally able to see "Registration successful" instead of a blank screen. Thank you!

**Comment by waynerox** [comment]
Running r1720 in a live website.
Worked for me also, many thanks @bmartin13. Do we know if @bmartin13 's fix will be merged into the codebase?

**Comment by ignacionelson** [comment]
Thank you!! 
Just applied the fix here https://github.com/projectsend/projectsend/commit/caf6824fcf86952ceee0f26c7eeb7b91b8b0e732

**Comment by MisterSysadmin** [comment]
Worked for me as well.

Great fix, thanks for the post.

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
