### ISSUE TITLE
Uncaught TypeError: fwrite()

### ISSUE THREAD

**Issue by Abhisheksha1553** [projectsend/projectsend#1274]
Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /Applications/XAMPP/xamppfiles/htdocs/projectsend/includes/functions.php:168 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/projectsend/includes/functions.php(168): fwrite(false, '1691860387\n') #1 /Applications/XAMPP/xamppfiles/htdocs/projectsend/includes/updates.functions.php(18): get_json('https://project...', '-1 days') #2 /Applications/XAMPP/xamppfiles/htdocs/projectsend/includes/core.update.php(17): get_latest_version_data() #3 /Applications/XAMPP/xamppfiles/htdocs/projectsend/header.php(39): require_once('/Applications/X...') #4 /Applications/XAMPP/xamppfiles/htdocs/projectsend/dashboard.php(15): include_once('/Applications/X...') #5 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/projectsend/includes/functions.php on line 168

**Comment by computid** [comment]
I'm having the exact same issue. Has anybody found a resolution?

**Comment by computid** [comment]
FYI, this is caused by the directory permissions on /cache not being set correctly. I set them to 755 and it seems to work, but that's probably a bit loose.

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
