### ISSUE TITLE
Php Fatal error.

### ISSUE THREAD

**Issue by CedricReymond** [projectsend/projectsend#1277]
Hello,
php 8.0.30
On a fresh install I am getting this:
array(6) { [":ids"]=> string(1) "0" [":public"]=> int(1) [":expires"]=> int(1) [":not_expires"]=> int(0) [":limit_start"]=> int(0) [":limit_number"]=> string(2) "10" } array(6) { [":ids"]=> string(1) "0" [":public"]=> int(1) [":expires"]=> int(1) [":not_expires"]=> int(0) [":limit_start"]=> int(0) [":limit_number"]=> int(-1) }
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1210 Incorrect arguments to mysqld_stmt_execute in C:\inetpub\wwwroot\projectsend\includes\functions.public.php:93 Stack trace: #0 C:\inetpub\wwwroot\projectsend\includes\functions.public.php(93): PDOStatement->execute() #1 C:\inetpub\wwwroot\projectsend\includes\functions.groups.php(231): get_public_files() #2 C:\inetpub\wwwroot\projectsend\templates\default\public-list.php(37): count_public_files_not_in_groups() #3 C:\inetpub\wwwroot\projectsend\public.php(64): require('...') #4 {main} thrown in C:\inetpub\wwwroot\projectsend\includes\functions.public.php on line 93

I added this line var_dump ($params); to the file functions.public.php to show the content.
anyone having the same issue?
Also the link sent by the system does not contain the base url, only contains /download.php?id=3&token=....

Any help appreciated.
Thanks,
Cedric

**Comment by BenBradnick** [comment]
I have the same problem here.

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
