### ISSUE TITLE
Fatal error when files are in groups

### ISSUE THREAD

**Issue by BrtnikFM** [projectsend/projectsend#1297]
Hello, we have files in several categories. After update to version r1605 users can not login.  There is an error
```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in /var/www/vhost/download/includes/functions.categories.php:196 Stack trace: #0 /var/www/vhost/download/includes/functions.categories.php(196): PDO->prepare() #1 /var/www/vhost/download/includes/functions.categories.php(177): add_missing_to_tree() #2 /var/www/vhost/download/templates/common.php(113): get_categories() #3 /var/www/vhost/download/templates/default/template.php(18): include_once('/var/www/vhost/...') #4 /var/www/vhost/download/my_files/index.php(12): require('/var/www/vhost/...') #5 {main} thrown in /var/www/vhost/download/includes/functions.categories.php on line 196
```

We tried to add parameters to database.php, into several places.
```
<?php
/**
 * Simple database connection and query class.
 * Uses the information defined on sys.config.php.
 */
use ProjectSend\Classes\Session;

/** Initiate the database connection */
if ( defined('DB_NAME') ) {
        global $dbh;
        try {
                switch ( DB_DRIVER ) {
                        default:
                        case 'mysql':
                $dbh = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASSWORD, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8", PDO::ATTR_PERSISTENT => 'buff', PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true));
            break;

                        case 'mssql':
                $dbh = new PDO("mssql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASSWORD, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));            break;
                }

                $dbh->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
                $dbh->setAttribute( PDO::ATTR_EMULATE_PREPARES, false );
                $dbh->setAttribute( PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, true);
                $dbh->setAttribute( PDO::ATTR_PERSISTENT, 'buff');
//                $dbh->setAttribute( PDO::ATTR_EMULATE_PREPARES, true);
        }
        catch(PDOException $e) {
        echo $e->getMessage();
        exit;
        }
}
```

But no luck. Could you please help us?

[PHP 7.4.33-SergeyD_6.1 - phpinfo().html.txt](https://github.com/projectsend/projectsend/files/13712853/PHP.7.4.33-SergeyD_6.1.-.phpinfo.html.txt)

**Comment by BrtnikFM** [comment]
Issue is caused by category which has no assigned files. Script fails with the missleading error.

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
