### ISSUE TITLE
Can't add new clients

### ISSUE THREAD

**Issue by adarshabeleyur** [projectsend/projectsend#485]
Hi,
I just now installed ProjectSend to my localhost, i cant add new clients there is no errors, after click submit button  it shows blank page means only header and menu list there is no success message, but in server it runs perfectly why cant in localhost....?
Please help me

**Comment by lenamtl** [comment]
Check the PHP logs to see errors...
Is this a new install or update?
Make sure you have PDO ext active

**Comment by adarshabeleyur** [comment]
There is no errors in PHP logs and PDO extension is active, there is no error while adding client but there is no success message it shows blank page

**Comment by bemcfarland** [comment]
Recently upgraded and now can't add a new client. No problem before.

**Comment by ignacionelson** [comment]
Hello! Have you tried setting the debug constant to true on the sys.vars.php file?
It should look like this:
define('DEBUG', false);

That should let you see any errors directly on the browser

**Comment by bemcfarland** [comment]
DEBUG is set to false as you listed.

What version of PHP will this run with?  I have PHP 7.2.

**Comment by ignacionelson** [comment]
I don't recall have any issues with php > 7 on my tests.
Try setting debug to true and see if anything comes up please.

**Comment by bemcfarland** [comment]
Set to true and no error message.

![image](https://user-images.githubusercontent.com/16061264/69557996-1b2ce380-0f6d-11ea-8a64-862449e3e23f.png)

**Comment by ignacionelson** [comment]
Oh I see. And your hosting provider can't check the log themselves and let you know at least the last few lines?

**Comment by bemcfarland** [comment]
I was able to SSH to the server.  What log am I looking for? I also need to know to ask Godaddy customer support.

**Comment by bemcfarland** [comment]
Found the error log:

[25-Nov-2019 09:10:46 America/Phoenix] PHP Notice:  Undefined index: max_file_size in /home/bemcfarland/public_html/files/includes/functions.php on line 530
[25-Nov-2019 09:10:46 America/Phoenix] PHP Notice:  Undefined property: stdClass::$url in /home/bemcfarland/public_html/files/includes/widgets/news.php on line 26
[25-Nov-2019 09:10:46 America/Phoenix] PHP Notice:  Undefined property: stdClass::$url in /home/bemcfarland/public_html/files/includes/widgets/news.php on line 26
[25-Nov-2019 09:10:46 America/Phoenix] PHP Notice:  Undefined property: stdClass::$url in /home/bemcfarland/public_html/files/includes/widgets/news.php on line 26
[25-Nov-2019 09:10:52 America/Phoenix] PHP Notice:  Undefined index: max_file_size in /home/bemcfarland/public_html/files/includes/functions.php on line 530
[25-Nov-2019 09:10:52 America/Phoenix] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/bemcfarland/public_html/files/clients-form.php on line 234
[25-Nov-2019 09:10:52 America/Phoenix] PHP Warning:  Invalid argument supplied for foreach() in /home/bemcfarland/public_html/files/clients-form.php on line 241
[25-Nov-2019 09:13:05 America/Phoenix] PHP Notice:  Undefined index: max_file_size in /home/bemcfarland/public_html/files/includes/functions.php on line 530
[25-Nov-2019 09:13:05 America/Phoenix] PHP Notice:  Constant USER_ROLE_LVL_9 already defined in /home/bemcfarland/public_html/files/includes/vars.php on line 13
[25-Nov-2019 09:13:05 America/Phoenix] PHP Notice:  Constant USER_ROLE_LVL_8 already defined in /home/bemcfarland/public_html/files/includes/vars.php on line 14
[25-Nov-2019 09:13:05 America/Phoenix] PHP Notice:  Constant USER_ROLE_LVL_7 already defined in /home/bemcfarland/public_html/files/includes/vars.php on line 15
[25-Nov-2019 09:13:05 America/Phoenix] PHP Notice:  Constant USER_ROLE_LVL_0 already defined in /home/bemcfarland/public_html/files/includes/vars.php on line 16
[25-Nov-2019 09:13:05 America/Phoenix] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/bemcfarland/public_html/files/clients-form.php on line 234
[25-Nov-2019 09:13:05 America/Phoenix] PHP Warning:  Invalid argument supplied for foreach() in /home/bemcfarland/public_html/files/clients-form.php on line 241
[25-Nov-2019 09:13:30 America/Phoenix] PHP Notice:  Undefined index: max_file_size in /home/bemcfarland/public_html/files/includes/functions.php on line 530
[25-Nov-2019 09:13:30 America/Phoenix] PHP Notice:  Constant USER_ROLE_LVL_9 already defined in /home/bemcfarland/public_html/files/includes/vars.php on line 13
[25-Nov-2019 09:13:30 America/Phoenix] PHP Notice:  Constant USER_ROLE_LVL_8 already defined in /home/bemcfarland/public_html/files/includes/vars.php on line 14
[25-Nov-2019 09:13:30 America/Phoenix] PHP Notice:  Constant USER_ROLE_LVL_7 already defined in /home/bemcfarland/public_html/files/includes/vars.php on line 15
[25-Nov-2019 09:13:30 America/Phoenix] PHP Notice:  Constant USER_ROLE_LVL_0 already defined in /home/bemcfarland/public_html/files/includes/vars.php on line 16
[25-Nov-2019 09:13:30 America/Phoenix] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'max_file_size' in 'field list' in /home/bemcfarland/public_html/files/includes/classes/database.php:24
Stack trace:
#0 /home/bemcfarland/public_html/files/includes/classes/database.php(24): PDO->prepare('INSERT INTO tbl...')
#1 /home/bemcfarland/public_html/files/includes/classes/actions-clients.php(162): PDOEx->prepare('INSERT INTO tbl...')
#2 /home/bemcfarland/public_html/files/clients-add.php(72): ClientActions->create_client(Array)
#3 {main}
  thrown in /home/bemcfarland/public_html/files/includes/classes/database.php on line 24

**Comment by ignacionelson** [comment]
Unknown column 'max_file_size'
That column was added around version r8xx, weird that you don't have it!
You could add it manually using phpmyadmin or running the command by logging into mysql from your ssh connection.

Something like this should work

ALTER TABLE `tbl_users` ADD COLUMN `max_file_size` int(20) NOT NULL DEFAULT '0'

**Comment by bemcfarland** [comment]
That did the trick!  Much thanks!  I have to remember to find your patreon.

**Comment by bemcfarland** [comment]
Just reviewed the log and while everything seems to be working, lots of warnings about email accounts.
