### ISSUE TITLE
Running grunt

### ISSUE THREAD

**Issue by ruevers** [projectsend/projectsend#735]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem

Try running grunt
### List the steps to reproduce the issue

1.ruevers@ruevers-VirtualBox:~/projectsend$ grunt
Running "copy:jquery" (copy) task
Copied 1 file

Running "copy:jquery_migrate" (copy) task
Copied 1 file

Running "copy:bootstrap" (copy) task
Copied 1 file

Running "concat:dependencies_js" (concat) task

Running "concat:dependencies_css" (concat) task

Running "concat:projectsend" (concat) task

Running "concat:compatibility" (concat) task

Running "uglify:projectsend" (uglify) task
>> 1 file created 17.47 kB → 11.37 kB

Running "uglify:compatibility" (uglify) task
>> 1 file created 7.11 kB → 6.75 kB

Running "uglify:dependencies_js" (uglify) task
>> 1 file created 359.23 kB → 350.81 kB

Running "uglify:dependencies_css" (uglify) task
{ SyntaxError: Unexpected token: punc «{», expected: punc «;»
  at JS_Parse_Error.get (<anonymous>:71:23)
  at formatError (util.js:640:16)
  at formatValue (util.js:544:18)
  at inspect (util.js:324:10)
  at format (util.js:191:12)
  at Console.log (console.js:130:21)
  at /home/ruevers/projectsend/node_modules/grunt-contrib-uglify/tasks/uglify.js:144:17
  at Array.forEach (<anonymous>:null:null)
  at Object.<anonymous> (/home/ruevers/projectsend/node_modules/grunt-contrib-uglify/tasks/uglify.js:78:16)
  at Object.<anonymous> (/home/ruevers/projectsend/node_modules/grunt/lib/grunt/task.js:252:15)
  at Object.thisTask.fn (/home/ruevers/projectsend/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/home/ruevers/projectsend/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/home/ruevers/projectsend/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/home/ruevers/projectsend/node_modules/grunt/lib/util/task.js:293:12)
  at /home/ruevers/projectsend/node_modules/grunt/lib/util/task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)

  message: 'Unexpected token: punc «{», expected: punc «;»',
  filename: 'dependencies.css',
  line: 5,
  col: 83,
  pos: 248 }
>> Uglifying source ./public/assets/css/dependencies.css failed.
Warning: Uglification failed.
Unexpected token: punc «{», expected: punc «;».
Line 5 in ./public/assets/css/dependencies.css
 Use --force to continue.

Aborted due to warnings.

2.

### Environment

* ProjectSend version: 
* php version: 7.2
* MySQL version: 5.7
ubuntu 18

### Additional information

try use grunt after clone the project and install dependencies and run grunt grunt dependencies_update (run ok, no errors)

if I use grunt -force, not work at all.

**Comment by ignacionelson** [comment]
Hi! This repo contains outdated code that will get replaced. What you see here was a failed attempt at refactoring the whole app. I will take care of this soon to avoid this confusion. The current code is on the other repo (legacy). I'm also rewriting the app from scratch, but I haven't uploaded that yet since it's not in a usable state. Sorry for the confusion!
