### ISSUE TITLE
Error install dev version

### ISSUE THREAD

**Issue by Philippe-M** [projectsend/projectsend#774]
Hello, I am trying to install the version during dev for testing and after validating the installation form I have the following error :

```
[Wed Mar 25 17:13:45.844040 2020] [php7:notice] [pid 727] [client 172.17.0.1:37950] PHP Notice:  Use of undefined constant OAUTH_LOGIN_CALLBACK_URL - assumed 'OAUTH_LOGIN_CALLBACK_URL' in /data/lamp/www/html/includes/hybridauth.php on line 5, referer: http://localhost:8080/install/make-config.php
[Wed Mar 25 17:13:45.844236 2020] [php7:error] [pid 727] [client 172.17.0.1:37950] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'projectsend.tbl_options' doesn't exist in /data/lamp/www/html/includes/database.php:24\nStack trace:\n#0 /data/lamp/www/html/includes/database.php(24): PDO->prepare('SELECT value FR...')\n#1 /data/lamp/www/html/includes/functions.options.php(24): PDOEx->prepare('SELECT value FR...')\n#2 /data/lamp/www/html/includes/hybridauth.php(8): get_option('facebook_signin...')\n#3 /data/lamp/www/html/bootstrap.php(71): require_once('/data/lamp/www/...')\n#4 /data/lamp/www/html/install/index.php(11): require_once('/data/lamp/www/...')\n#5 {main}\n  thrown in /data/lamp/www/html/includes/database.php on line 24, referer: http://localhost:8080/install/make-config.php

```

```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| phpmyadmin         |
| projectsend        |
+--------------------+

MariaDB [projectsend]> show tables;
Empty set (0.01 sec)

```

it’s like tables cannot be created

**Comment by ignacionelson** [comment]
Hello.
Dev version is not installable yet. Please try the latest release! Sorry!
