### ISSUE TITLE
V1070 Client Registration - registration blank web page

### ISSUE THREAD

**Issue by cdmjcdmj** [projectsend/projectsend#809]
Recently installed v1070 and everything works except when a client self registers the screen goes blank. The client does show up as a request register or registered client, but the web page simply goes blank and does not refresh? Everything else works fine.

**Comment by ignacionelson** [comment]
Hi! Looks like you are getting a php error, but it's not being displayed.
Try enabling debug mode please, or check the php error log.
To enable debug: Edit the file sys.vars.php and change
define('DEBUG', false);
to
define('DEBUG', true);

**Comment by cdmjcdmj** [comment]
Here's error log

[17-Sep-2020 14:01:06 America/Chicago] PHP Notice:  Constant USER_ROLE_LVL_9 already defined in /home3/georgeb/public_html/library/includes/vars.php on line 13
[17-Sep-2020 14:01:06 America/Chicago] PHP Notice:  Constant USER_ROLE_LVL_8 already defined in /home3/georgeb/public_html/library/includes/vars.php on line 14
[17-Sep-2020 14:01:06 America/Chicago] PHP Notice:  Constant USER_ROLE_LVL_7 already defined in /home3/georgeb/public_html/library/includes/vars.php on line 15
[17-Sep-2020 14:01:06 America/Chicago] PHP Notice:  Constant USER_ROLE_LVL_0 already defined in /home3/georgeb/public_html/library/includes/vars.php on line 16
[17-Sep-2020 14:01:06 America/Chicago] PHP Notice:  Undefined index: notify_account in /home3/georgeb/public_html/library/includes/classes/actions-clients.php on line 57
[17-Sep-2020 14:01:06 America/Chicago] PHP Notice:  Undefined index: notify_account in /home3/georgeb/public_html/library/includes/classes/actions-clients.php on line 146
[17-Sep-2020 14:01:06 America/Chicago] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`georgeb_library`.`tbl_members_requests`, CONSTRAINT `tbl_members_requests_ibfk_2` FOREIGN KEY (`group_id`) REFERENCES `tbl_groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in /home3/georgeb/public_html/library/includes/classes/actions-members.php:327
Stack trace:
#0 /home3/georgeb/public_html/library/includes/classes/actions-members.php(327): PDOStatement->execute()
#1 /home3/georgeb/public_html/library/register.php(98): MembersActions->group_request_membership(Array)
#2 {main}
  thrown in /home3/georgeb/public_html/library/includes/classes/actions-members.php on line 327

**Comment by cdmjcdmj** [comment]
I just commented out line 98 with the error message clue (below) in register.php and everything looks normal!!

/home3/georgeb/public_html/library/register.php(98): MembersActions->group_request_membership(Array)

**Comment by serg499** [comment]
Unfortunately I have this bug again on the latest available release r1720.
Line 98 in register.php now looks completely different and I can't find "MembersActions->group_request_membership(Array)" line there.

**Comment by rcs27** [comment]
Hi there, any update or quick fix on this?

**Comment by rcs27** [comment]
> Unfortunately I have this bug again on the latest available release r1720. Line 98 in register.php now looks completely different and I can't find "MembersActions->group_request_membership(Array)" line there.

@serg499  Update this block in limitUploadToSave(): on file /includes/Classes/Users.php

Changes this 

```
if (CURRENT_USER_LEVEL == 7) {
    return;
}

```
to use $_SESSION:

```
if (isset($_SESSION['user_level']) && $_SESSION['user_level'] == 7) {
    return;
}
```

this fixed the issue @ignacionelson @
