### ISSUE TITLE
install/index.php  HTTP ERROR 500

### ISSUE THREAD

**Issue by pramodkmr73** [projectsend/projectsend#812]
Environment :  Red Hat Enterprise Linux release 8.1 (Ootpa)
DB :mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for Linux (x86_64) using readline 5.1

PHP Version 7.2.11
Apache :2.4 

Installation  index.php page give HTTP ERROR 500 

How to look for the error .

**Comment by ignacionelson** [comment]
Sorry that I missed your message. Please check with the new version, it should work just fine!
If not, enable debug mode on includes/app.php to see if you get any errors

**Comment by Skyridr** [comment]
I'm also getting ERROR 500 after I've updated to the latest version:

Debug shows:

```Notice: Undefined index: type in /includes/functions.php on line 1228

Notice: Undefined index: type in /includes/functions.php on line 1231

Notice: Undefined variable: replace in /includes/functions.php on line 1235```

Running on PHP 7.4

**Comment by Skyridr** [comment]
@ignacionelson 

After I've updated to the latest version, getting 500 error pages as well.

> Notice: Undefined index: HTTP_CLIENT_IP in /includes/functions.php on line 1710
> 
> Notice: Only variables should be passed by reference in /includes/functions.php on line 1618
> 
> Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'details' in 'field list' in /includes/database.php:25 Stack trace: #0 /includes/database.php(25): PDO->prepare() #1 /includes/Classes/ActionsLog.php(154): PDOEx->prepare() #2 /includes/Classes/Download.php(166): ProjectSend\Classes\ActionsLog->addEntry() #3 /includes/Classes/Download.php(39): ProjectSend\Classes\Download->downloadFile() #4 /process.php(91): ProjectSend\Classes\Download->download() #5 {main} thrown in /includes/database.php on line 25

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
