### ISSUE TITLE
Entering wrong password results in an endless spinner on the login page

### ISSUE THREAD

**Issue by Znuff** [projectsend/projectsend#841]
As per title. No feedback is offered for a wrong password.

**Comment by ignacionelson** [comment]
What php version are you using? Have you enabled debug mode?

**Comment by Znuff** [comment]
This is using PHP 7.4

With debug mode I get:

```
<br />
<b>Notice</b>:  Undefined property: stdClass::$user_id in <b>/[path]/process.php</b> on line <b>25</b><br />
<br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'owner_id' cannot be null in /[path]/includes/Classes/ActionsLog.php:155
Stack trace:
#0 /[path]/includes/Classes/ActionsLog.php(155): PDOStatement-&gt;execute()
#1 /[path]/process.php(33): ProjectSend\Classes\ActionsLog-&gt;addEntry()
#2 {main}
  thrown in <b>/[path]/includes/Classes/ActionsLog.php</b> on line <b>155</b><br />
```

**Comment by ignacionelson** [comment]
Found the issue
line 23 of process.php
`if ($decoded->status = 'success') {`
should be
`if ($decoded->status == 'success') {`

**Comment by ignacionelson** [comment]
Fixed in r1295
