### ISSUE TITLE
Screen goes blank when trying to approve a request

### ISSUE THREAD

**Issue by Hagrid78** [projectsend/projectsend#935]
Hello i would like to report something that might be a bug.  when you try to approve someones request into a group the screen would go blank then when you refresh the request would never be approved.  i tried 3 different browsers  brave, chrome and firefox same results.   how would i fix this ?
thanks!
![image](https://user-images.githubusercontent.com/26916567/115337854-c1cfe080-a16f-11eb-8187-5a2e37e81211.png)

**Comment by cdmjcdmj1** [comment]
> Hello i would like to report something that might be a bug. when you try to approve someones request into a group the screen would go blank then when you refresh the request would never be approved. i tried 3 different browsers brave, chrome and firefox same results. how would i fix this ?
> thanks!
> ![image](https://user-images.githubusercontent.com/26916567/115337854-c1cfe080-a16f-11eb-8187-5a2e37e81211.png)

Having same issue. Installed three times using different credentials and DB. Did you ever resolve this?

**Comment by cdmjcdmj1** [comment]
Turned on PHP server errors and got this

Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number in /home3/xxxxxxx/public_html/project_send/includes/Classes/MembersActions.php:397

 Stack trace: #0 /home3/xxxxxxx/public_html/project_send/includes/Classes/MembersActions.php(397): 

PDOStatement->execute() 
#1 /home3/xxxxxxxxx/public_html/project_send/clients-membership-requests.php(66): ProjectSend\Classes\MembersActions->group_process_memberships(Array, true) 
#2 {main} thrown in /home3/xxxxxxxxx/public_html/project_send/includes/Classes/MembersActions.php on line 397

I looked up error. Since I am not a programmer at least I got a hint. I fiddled with the code, overriding parameter values, and was able remove this error but the correction cascaded into other errors, particularly having "null" values.

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
